### ISSUE TITLE
Dropped Files And Memory Dumps Missing?

### ISSUE THREAD

**Issue by eoinmiller-sfdc** [spender-sandbox/cuckoo-modified#44] opened 2016-02-10 21:47 UTC
So I've been noticing that dropped files does not include the embedded exe's from some word docs that are written to disk and executed.

Debug logs:
2016-02-10 16:32:04,204 [lib.cuckoo.core.resultserver] DEBUG: New process (pid=2900, ppid=2336, name=WINWORD.EXE, path=C:\Program Files (x86)\Microsoft Office\Office15\WINWORD.EXE)
2016-02-10 16:32:11,052 [lib.cuckoo.core.resultserver] DEBUG: New process (pid=1924, ppid=2900, name=kitabc2.exe, path=C:\Users\justin\AppData\Local\Temp\kitabc2.exe)

Additionally, this kitabc2.exe does not show up in the list of modified files and the process does not have a memory dump. The path and file is in the list of executed commands however. Any clue as to why this may be happening?

**Comment by spender-sandbox** [comment] 2016-02-10 21:49
Can you provide a hash of the document?

-Brad

**Comment by eoinmiller-sfdc** [comment] 2016-02-10 21:52
Sure, or I could send it your way if you like.

MD5	        2a643716440b24101ea0c2e6692957bf
SHA1	d68ff26fec551a2613a85dc97de546eff6131b35
SHA256	df311fd678610ffdb0ef2914dd48eff490a7db3d6b92eed3021539e91261936b

**Comment by eoinmiller-sfdc** [comment] 2016-02-10 22:03
Increasing upload_max_size and analysis_size_limit got me the memory dumps, however the dropped files are missing the binary still.

**Comment by eoinmiller-sfdc** [comment] 2016-02-16 18:18
Another word doc that drops a cryptowall payload:

MD5	096c642014c8c881c9d1dd5deab71320
SHA-1	aefc9f9433817d2e33eb20577f8a5bbe54ef3781
SHA-256	d9a538befe2e29fa7284b509d1ab9603771fbc3f555d609e8642d5a6e9ddb543

The doc has a macro that downloads the xor'd binary, writes it to disk and executes it. However the file that is written to disk never makes it into the dropped file section:
<img width="624" alt="screenshot" src="https://cloud.githubusercontent.com/assets/15840028/13086044/4f2f9b0c-d4af-11e5-90ee-04d0101c0270.png">

**Comment by spender-sandbox** [comment] 2016-02-16 18:30
What's the analysis.log look like?

**Comment by eoinmiller-sfdc** [comment] 2016-02-16 18:39
Sure thing, see attached.
[analysis.log.txt](https://github.com/spender-sandbox/cuckoo-modified/files/133092/analysis.log.txt)

**Comment by spender-sandbox** [comment] 2016-02-16 18:41
Are you running the very latest version?  Only that version will dump dropped files when the system is about to be shut down.

**Comment by eoinmiller-sfdc** [comment] 2016-02-16 19:53
Just did a git clone and detonated the same original sample (2a643716440b24101ea0c2e6692957bf) that contains, drops and executes the binary kitabc2.exe. Memory analysis and such shows up, but the binary isn't in dropped files. Analysis.log is also attached.
[analysis.log.txt](https://github.com/spender-sandbox/cuckoo-modified/files/133184/analysis.log.txt)

<img width="509" alt="screenshot" src="https://cloud.githubusercontent.com/assets/15840028/13088974/8df84868-d4bc-11e5-9013-4fe61db80711.png">

**Comment by spender-sandbox** [comment] 2016-02-19 23:47
Try the latest version.  There was an upstream bug that was silently truncating uploads in some cases.

-Brad

**Comment by eoinmiller-sfdc** [comment] 2016-02-20 00:55
git clone, detonated and kitabc2.exe is still not in dropped files. Would the update rely on anything in agent.py? I didn't update that on the VM's prior to testing.

**Comment by spender-sandbox** [comment] 2016-02-20 05:15
Ok, I see what the issue is.  It's a little complicated but I should have a fix next week.

-Brad

**Comment by eoinmiller-sfdc** [comment] 2016-02-22 23:00
Here is another that may be interesting:

cebfd5ebba3533b89b4c16e91c90128e92433bfe

This excel file will download and execute a binary, but the binary never shows up in dropped files and there isn't a memory dump of it either.
<img width="677" alt="screenshot" src="https://cloud.githubusercontent.com/assets/15840028/13235826/f89fd430-d974-11e5-9bcc-02501c67560e.png">

**Comment by spender-sandbox** [comment] 2016-03-08 20:41
Can you check your behavioral logs to see if the UrlDownloadToFileW even succeeded?  In my tests here it didn't, hence why nothing was written to disk.

-Brad

**Comment by eoinmiller-sfdc** [comment] 2016-03-08 20:54
Shoot, you are correct. I saw the request but it gets a 403 response.

**Comment by spender-sandbox** [comment] 2016-03-29 16:56
I've looked again at the original sample (kitabc2) and found the issue.  I'll include the improvement/fix in with the other changes I have queued up.

-Brad

**Comment by spender-sandbox** [comment] 2016-03-31 16:25
Resolved with the latest commit.

**Closed by spender-sandbox** 2016-03-31 16:25 UTC

**Comment by eoinmiller-sfdc** [comment] 2016-04-04 23:14
@spender-sandbox I haven't upgraded yet to check this but something odd I noticed is that if you turn on resubmit exe's in the conf then the exe is still missing from dropped files, but is automatically reprocessed. This doesn't happen with the original kitabc2 exe, but it does happen with this one:

MD5 1b0fbd5e0af361058a8115b941232e34 (lewd.exe is the payload without that is dropped and executed).

**Comment by spender-sandbox** [comment] 2016-04-04 23:16
It could have been obtained from suricata files

-Brad

**Comment by eoinmiller-sfdc** [comment] 2016-04-04 23:21
I double checked and that wasn't the source in this instance. This office doc has the pony loader in the document and stored as a string in hex format at 80412 bytes into the file.
![image](https://cloud.githubusercontent.com/assets/15840028/14266988/77cd069c-fa9a-11e5-953b-5e22063abe32.png)

**Comment by spender-sandbox** [comment] 2016-04-04 23:24
Don't know then -- unless you have some custom changes, the only two things resubmitexe pulls from is dropped files and suricata files, using the same dict information that the web interface itself would use to display them.

-Brad

**Comment by eoinmiller-sfdc** [comment] 2016-04-05 15:29
I tried upgrading and detonating the document that drops kitabc2 and it still doesn't appear in the list of dropped files. I've attached the log and the report in PDF format.

[report.pdf](https://github.com/spender-sandbox/cuckoo-modified/files/204794/report.pdf)
[log.txt](https://github.com/spender-sandbox/cuckoo-modified/files/204795/log.txt)

**Comment by eoinmiller-sfdc** [comment] 2016-04-26 17:58
Gave this a shot again, still not appearing in dropped files and the following screenshot is the only mention of kitabc2.exe in the Behavioral Analysis tab. This also holds true for current malicious docs using pony dropper w/vawtrak 2nd stage loaders.

![image](https://cloud.githubusercontent.com/assets/15840028/14828899/ed69b4fe-0bb6-11e6-8c34-dfaa96945cae.png)

**Comment by spender-sandbox** [comment] 2016-04-26 17:59
Can you give me a list of all the CoCreateInstance calls?  I might need to add more CLSIDs for different Office versions.

-Brad

**Comment by eoinmiller-sfdc** [comment] 2016-04-26 18:05
Sure thing. Attached is PDF of all CoCreateInstance. Please let me know if there is anything else I can provide.

[CoCreateInstance.pdf](https://github.com/spender-sandbox/cuckoo-modified/files/237194/CoCreateInstance.pdf)

**Comment by spender-sandbox** [comment] 2016-04-26 18:10
It's using the COM object I already have detection for.  Can you show me the analysis.log? It should show injection into the DCOM service, which would then let us see the execution of the launched Word process.

-Brad

**Comment by eoinmiller-sfdc** [comment] 2016-04-26 18:14
Absolutely, see attached. It appears some errors occurred during detonation.
[analysis.log.txt](https://github.com/spender-sandbox/cuckoo-modified/files/237207/analysis.log.txt)

**Comment by spender-sandbox** [comment] 2016-04-26 18:25
How much memory do you have allocated for the guest, and what version of Windows is it?

-Brad

**Comment by eoinmiller-sfdc** [comment] 2016-04-26 18:31
2GB of RAM, Win7ProSP1 w/o patches, office 2013.

**Comment by spender-sandbox** [comment] 2016-04-26 18:44
You'll have to do some debugging yourself on this one, either you're generating massive logs that the agent can't send out fast enough (such that the concatenated 'data' from various threads ends up getting too large) or you've got some other issue with your VM setup that is causing starvation of resources.

-Brad

**Comment by eoinmiller-sfdc** [comment] 2016-04-26 19:03
It appears to be an issue with 64bit Windows 7 (office does create a massive process to open the doc, like 800mb+) but I am having a different kind of error with 32bit Windows7. I detonated the same sample on the 32bit build I have (again Win7ProSP1 w/o patches and Office 2013). However kitabc isn't in the dropped files and a bunch of memory dumps for processes fail. Attached are CoCreateInstance calls along aith analysis.log for the same sample on 32bit Windows 7.
[CoCreateInstance_32bit.pdf](https://github.com/spender-sandbox/cuckoo-modified/files/237270/CoCreateInstance_32bit.pdf)
[analysis.log_32bit.txt](https://github.com/spender-sandbox/cuckoo-modified/files/237273/analysis.log_32bit.txt)

**Comment by spender-sandbox** [comment] 2016-04-26 19:20
Looks like you're getting the DCOM injection, but for some reason it doesn't see the creation of the Word process.  Anything interesting in PID 668?

-Brad

**Comment by eoinmiller-sfdc** [comment] 2016-04-26 19:46
PID 868? Full dump attached.
[868.dmp.zip](https://github.com/spender-sandbox/cuckoo-modified/files/237341/868.dmp.zip)

Lots of CreateRemoteThread's going on in there:
[threading.pdf](https://github.com/spender-sandbox/cuckoo-modified/files/237344/threading.pdf)

**Comment by spender-sandbox** [comment] 2016-04-26 20:00
None of those calls are interesting, they're all to the current process.

-Brad
