### ISSUE TITLE
Word Doc Static Analysis Failing

### ISSUE THREAD

**Issue by eoinmiller-sfdc** [spender-sandbox/cuckoo-modified#350] opened 2016-11-07 13:48 UTC
Been seeing this with a few maldocs lately. Below log is based off of the following sample:
```
MD5	1e1614b8b6d47371362c52aead9e9a12
SHA-1	98a9b22cb592998ee4e1f1939841365c60468bf1
SHA-256	afc4acfb9a41a00aa9cb3f2f11c76f92dc40718c02af9d5931cf76321c261675
```

Cuckoo Process Log:
```
2016-11-03 11:32:39,762 [root] DEBUG: Opening OLE file /home/cuckoo/cuckoo-modified/storage/binaries/afc4acfb9a41a00aa9cb3f2f11c76f92dc40718c02af9d5931cf76321c261675
2016-11-03 11:32:39,763 [root] DEBUG: Found VBA storage: Macros/VBA
2016-11-03 11:32:39,764 [root] DEBUG: Checking vba_root="Macros/"
2016-11-03 11:32:39,764 [root] DEBUG: Found PROJECT stream: Macros/PROJECT
2016-11-03 11:32:39,764 [root] DEBUG: Found VBA/_VBA_PROJECT stream: Macros/VBA/_VBA_PROJECT
2016-11-03 11:32:39,764 [root] DEBUG: Found VBA/dir stream: Macros/VBA/dir
2016-11-03 11:32:39,764 [root] DEBUG: VBA root storage: "Macros/"
2016-11-03 11:32:39,765 [root] DEBUG: chunk size = 520, compressed flag = 1
2016-11-03 11:32:39,765 [root] DEBUG: 32-bit Windows
2016-11-03 11:32:39,765 [root] DEBUG: reference type = 0016
2016-11-03 11:32:39,765 [root] DEBUG: reference type = 000D
2016-11-03 11:32:39,765 [root] DEBUG: reference type = 0016
2016-11-03 11:32:39,766 [root] DEBUG: reference type = 000E
2016-11-03 11:32:39,766 [root] DEBUG: reference type = 0016
2016-11-03 11:32:39,766 [root] DEBUG: reference type = 000D
2016-11-03 11:32:39,766 [root] DEBUG: reference type = 000F
2016-11-03 11:32:39,766 [root] DEBUG: parsing 1 modules
2016-11-03 11:32:39,766 [root] DEBUG: Project CodePage = 1251
2016-11-03 11:32:39,766 [root] DEBUG: ModuleName = ThisDocument
2016-11-03 11:32:39,766 [root] DEBUG: StreamName = 'ThisDocument'
2016-11-03 11:32:39,767 [root] DEBUG: StreamName.decode('cp1251') = u'ThisDocument'
2016-11-03 11:32:39,767 [root] DEBUG: StreamNameUnicode = 'T\x00h\x00i\x00s\x00D\x00o\x00c\x00u\x00m\x00e\x00n\x00t\x00'
2016-11-03 11:32:39,767 [root] DEBUG: TextOffset = 60140
2016-11-03 11:32:39,767 [root] DEBUG: opening VBA code stream u'Macros/VBA/ThisDocument'
2016-11-03 11:32:39,767 [root] DEBUG: length of code_data = 85486
2016-11-03 11:32:39,768 [root] DEBUG: offset of code_data = 60140
2016-11-03 11:32:39,768 [root] DEBUG: chunk size = 2705, compressed flag = 1
2016-11-03 11:32:39,770 [root] DEBUG: chunk size = 2766, compressed flag = 1
2016-11-03 11:32:39,772 [root] DEBUG: chunk size = 2772, compressed flag = 1
2016-11-03 11:32:39,774 [root] DEBUG: chunk size = 2847, compressed flag = 1
2016-11-03 11:32:39,777 [root] DEBUG: chunk size = 2846, compressed flag = 1
2016-11-03 11:32:39,779 [root] DEBUG: chunk size = 2616, compressed flag = 1
2016-11-03 11:32:39,782 [root] DEBUG: chunk size = 2368, compressed flag = 1
2016-11-03 11:32:39,785 [root] DEBUG: chunk size = 2726, compressed flag = 1
2016-11-03 11:32:39,787 [root] DEBUG: chunk size = 2491, compressed flag = 1
2016-11-03 11:32:39,790 [root] DEBUG: chunk size = 1208, compressed flag = 1
2016-11-03 11:32:39,934 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Static":
Traceback (most recent call last):
  File "/home/cuckoo/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 197, in process
    data = current.run()
  File "/home/cuckoo/cuckoo-modified/utils/../modules/processing/static.py", line 1449, in run
    static = Office(self.file_path).run()
  File "/home/cuckoo/cuckoo-modified/utils/../modules/processing/static.py", line 1157, in run
    results = self._parse(self.file_path)
  File "/home/cuckoo/cuckoo-modified/utils/../modules/processing/static.py", line 1111, in _parse
    iocs = vbadeobf.parse_macro(vba_code)
  File "/home/cuckoo/cuckoo-modified/utils/../lib/cuckoo/common/office/vbadeobf.py", line 180, in parse_macro
    substituted = handle_techniques(line, **opts)
  File "/home/cuckoo/cuckoo-modified/utils/../lib/cuckoo/common/office/vbadeobf.py", line 121, in handle_techniques
    line = re.sub(r'(?i)Asc[A-Z$]\("""(\w)\w*"""\)', lambda m: ord(m.group(1)), line)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 1: expected string, int found
2016-11-03 11:32:39,934 [lib.cuckoo.core.plugins] DEBUG: Executing processing module "Strings" on analysis at "/home/cuckoo/cuckoo-modified/storage/analyses/4979"
```

**Comment by spender-sandbox** [comment] 2016-11-07 13:50
Yeah, the version of oletools we use needs to be updated.

-Brad

**Comment by mallorybobalice** [comment] 2016-11-13 10:17
@spender-sandbox  - are there any plans to merge this in, if not - any tips on doing it on your own (I'm guessing we just git clone https://github.com/decalage2/oletools  and copy it into https://github.com/spender-sandbox/cuckoo-modified/tree/master/lib/cuckoo/common/office ? 

anyone try(test for a bit)/issues?

**Comment by marek2003** [comment] 2016-11-23 13:26
I tried to use the newer version of oletools and I get this error : 
2016-11-23 14:10:56,903 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Static":
  File "/xxxx/cuckoo-modified/lib/cuckoo/core/plugins.py", line 197, in process
    data = current.run()
  File "/xxxx/cuckoo-modified/modules/processing/static.py", line 1493, in run
    static = Office(self.file_path).run()
  File "/xxxxx/cuckoo-modified/modules/processing/static.py", line 1160, in run
    results = self._parse(self.file_path)
  File "/xxxxxx/cuckoo-modified/modules/processing/static.py", line 1083, in _parse
    officeresults["Metadata"] = meta.get_meta()
AttributeError: OleMetadata instance has no attribute 'get_meta'

**Comment by KillerInstinct** [comment] 2016-11-23 14:38
@marek2003 

That is because the get_meta function was something I added to olefile.py as we didn't need all the information that the dump function provided. Copy this function into the bottom of the OleMetadata class, see if it works. If it does, I'm sure a PR would be welcome.

https://github.com/spender-sandbox/cuckoo-modified/blob/master/lib/cuckoo/common/office/olefile.py#L678

**Comment by marek2003** [comment] 2016-11-23 15:36
@KillerInstinct  I copied the fuction to the new olefile (just after the function "def dump(self):")
 but i get the same error.

[olefile.zip](https://github.com/spender-sandbox/cuckoo-modified/files/609252/olefile.zip)

**Comment by marek2003** [comment] 2016-11-23 17:32
If I try to kill all python, clean Db and start I get this:
File "/xxxxxx/cuckoo-modified/lib/cuckoo/common/office/msgextract.py", line 37, in <module>
    import olefile as OleFile
  File "/xxxxxx/cuckoo-modified/lib/cuckoo/common/office/olefile.py", line 708
    def dump(self):
                  ^
IndentationError: unindent does not match any outer indentation level

**Comment by doomedraven** [comment] 2016-11-23 17:53
you need to check indentation error which you have in your `/xxxxxx/cuckoo-modified/lib/cuckoo/common/office/olefile.py` near to like 708

**Comment by marek2003** [comment] 2016-11-23 18:43
tks @doomedraven    I Solved the indentation error(couple of whitespaces)  but the static analysis still failed with the new olefile with the add of the function "def get_meta(self):  :" ....
Traceback (most recent call last):
  File "/xxxxx/cuckoo-modified/lib/cuckoo/core/plugins.py", line 197, in process
    data = current.run()
  File "/xxxxxx/cuckoo-modified/modules/processing/static.py", line 1493, in run
    static = Office(self.file_path).run()
  File "/xxxxx/cuckoo-modified/modules/processing/static.py", line 1160, in run
    results = self._parse(self.file_path)
  File "/xxxxxxx/cuckoo-modified/modules/processing/static.py", line 1083, in _parse
    officeresults["Metadata"] = meta.get_meta()
  **File "/xxxxxxxxxx/cuckoo-modified/lib/cuckoo/common/office/olefile.py", line 726, in get_meta
    ret["SummaryInformation"][prop] = convert_to_printable(str(value))
NameError: global name 'convert_to_printable' is not defined**

**Comment by doomedraven** [comment] 2016-11-23 19:45
Read the error last lines, hou have what id wrong

Best regards
Andriy

**Comment by marek2003** [comment] 2016-11-23 20:48
added:
"**from lib.cuckoo.common.utils import convert_to_printable**"  to the olefile but now I get this:-)
Traceback (most recent call last):
  File "/home/socadmin/cuckoo-modified/lib/cuckoo/core/plugins.py", line 197, in process
    data = current.run()
  File "/home/socadmin/cuckoo-modified/modules/processing/static.py", line 1493, in run
    static = Office(self.file_path).run()
  File "/home/socadmin/cuckoo-modified/modules/processing/static.py", line 1160, in run
    results = self._parse(self.file_path)
  File "/home/socadmin/cuckoo-modified/modules/processing/static.py", line 1086, in _parse
    buf = self.convert_dt_string(metares["SummaryInformation"]["create_time"])
KeyError: 'create_time'

**Comment by marek2003** [comment] 2016-11-24 13:02
@doomedraven , any idea Andriy? Im stuck on this error and I really don't know what to do. Having the new oletools integrated with cuckoo 'd be great but Im newbie in python so It takes 5 years to go on with this kind of problem :-) :-)

**Comment by doomedraven** [comment] 2016-11-24 13:05
try this
change 
`buf = self.convert_dt_string(metares["SummaryInformation"]["create_time"])` 
* to 

`buf = self.convert_dt_string(metares.get("SummaryInformation", {}).get("create_time", "")`

**Comment by agaglia** [comment] 2016-11-24 13:46
Hi, after the change we have:

_buf = self.convert_dt_string(metares["SummaryInformation"]["last_saved_time"])
      ^
SyntaxError: invalid syntax_

We change like "create_time" string and the error is the same:

_buf = self.convert_dt_string(metares.get("SummaryInformation", {}).get("last_saved_time", "")
      ^
SyntaxError: invalid syntax_

Any idea? THX

**Comment by doomedraven** [comment] 2016-11-24 13:49
missed `)` at the end of `buf = self.convert_dt_string(metares.get("SummaryInformation", {}).get("last_saved_time", "")`

should be `buf = self.convert_dt_string(metares.get("SummaryInformation", {}).get("last_saved_time", ""))`

**Comment by agaglia** [comment] 2016-11-24 13:54
THX! Syntax_error seems  solved!

**Comment by doomedraven** [comment] 2016-11-24 13:55
but do you still have any other error?

**Comment by agaglia** [comment] 2016-11-24 14:01
Yes...there are other errors:
2016-11-24 14:58:09,443 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Static":
Traceback (most recent call last):
  File "/home/xxxxxxxx/cuckoo-modified/lib/cuckoo/core/plugins.py", line 197, in process
    data = current.run()
  File "/home/xxxxxxxx/cuckoo-modified/modules/processing/static.py", line 1496, in run
    static = Office(self.file_path).run()
  File "/home/xxxxxxxx/cuckoo-modified/modules/processing/static.py", line 1163, in run
    results = self._parse(self.file_path)
  File "/home/xxxxxxxx/cuckoo-modified/modules/processing/static.py", line 1084, in _parse
    officeresults["Metadata"] = meta.get_meta()
AttributeError: OleMetadata instance has no attribute 'get_meta'

Any idea?

**Comment by doomedraven** [comment] 2016-11-24 14:03
so you return to https://github.com/spender-sandbox/cuckoo-modified/issues/350#issuecomment-262529451

**Comment by agaglia** [comment] 2016-11-24 14:04
yeah...exactly

**Comment by doomedraven** [comment] 2016-11-24 14:05
you have the answer there ;) and point what you need to copy/fix

**Comment by agaglia** [comment] 2016-11-24 14:18
This is the "office" zipped directory with all files we have. I think I've installed everything correctly.
Could you take a look to see if the files are all correct?
[office.zip](https://github.com/spender-sandbox/cuckoo-modified/files/611508/office.zip)

THX

**Comment by doomedraven** [comment] 2016-11-24 14:30
just tried on my side works without any modifications, which version of oletools do you use? i have `oletools (0.50)`

**Comment by agaglia** [comment] 2016-11-24 14:45
Same version 0.50

**Comment by doomedraven** [comment] 2016-11-24 14:46
try this as debug
add to
`"/home/xxxxxxxx/cuckoo-modified/modules/processing/static.py`
before
`officeresults["Metadata"] = meta.get_meta()`
this
`print dir(meta)`

**Comment by marek2003** [comment] 2016-11-24 15:06
As soon as i get back on PC i will try. Tks for the moment

**Comment by marek2003** [comment] 2016-11-24 19:38
@doomedraven  same error. I also tried on another cuckoo server :-/
on static.py 
# must be left this way or we won't see the results
            print dir(meta)
            officeresults["Metadata"] = meta.get_meta()
error on processing debug:
Traceback (most recent call last):
  File "/home/socadmin/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 197, in process
    data = current.run()
  File "/home/socadmin/cuckoo-modified/utils/../modules/processing/static.py", line 1497, in run
    static = Office(self.file_path).run()
  File "/home/socadmin/cuckoo-modified/utils/../modules/processing/static.py", line 1164, in run
    results = self._parse(self.file_path)
  File "/home/socadmin/cuckoo-modified/utils/../modules/processing/static.py", line 1084, in _parse
    print dir(meta)
AttributeError: OleMetadata instance has no attribute 'get_meta'

**Comment by doomedraven** [comment] 2016-11-24 19:49
i don't know why you have this error, i have the same repo cloned and it works as i checked and all this attributes is where they should be, did you modify some source code?

**Comment by marek2003** [comment] 2016-11-24 20:03
I added on olefile.py 
from lib.cuckoo.common.utils import convert_to_printable
#and @KillerInstinct suggest:#
def get_meta(self):
        ret = dict()
        ret["SummaryInformation"] = dict()
        for prop in self.SUMMARY_ATTRIBS:
            value = getattr(self, prop)
            ret["SummaryInformation"][prop] = convert_to_printable(str(value))
        ret["DocumentSummaryInformation"] = dict()
        for prop in self.DOCSUM_ATTRIBS:
            value = getattr(self, prop)
            ret["DocumentSummaryInformation"][prop] = convert_to_printable(str(value))
        return ret

**Comment by marek2003** [comment] 2016-11-24 20:04
can you zip your office folder so that I can try it?

**Comment by doomedraven** [comment] 2016-11-24 20:21
Is the same as in repo so just clone and move it, it works just fine for me and i mever touched that files

**Comment by marek2003** [comment] 2016-11-24 22:25
If u move the repo "as is", the new olefile it's not on the ./office path but its in the /office/thirdparty/olefile. so in order to call this module you 've to change the import on static.py from 
import lib.cuckoo.common.office.olefile as olefile to import lib.cuckoo.common.office.thirdparty.olefile as olefile.
if you do this I think you can reproduce the traceback error.

**Comment by marek2003** [comment] 2016-11-24 23:02
@doomedraven  i dunno why, after deleted and recreated the whole office path and modified the olefile re-adding
from lib.cuckoo.common.utils import convert_to_printable
and @KillerInstinct  get_meta function:
(https://github.com/spender-sandbox/cuckoo-modified/blob/master/lib/cuckoo/common/office/olefile.py#L678)
it works and the static tab now shows the metadata and macros.

I  see some traceback with vbadeobf with a couple of DOC but I dunno if its a common issue or not
File "/xxxxx/cuckoo-modified/utils/../lib/cuckoo/common/office/vbadeobf.py", line 121, in handle_techniques
    line = re.sub(r'(?i)Asc[A-Z$]\("""(\w)\w*"""\)', lambda m: ord(m.group(1)), line)
  File "/usr/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 1: expected string, int found

**Comment by doomedraven** [comment] 2016-11-24 23:47
@marek2003 i don't need latest olefile, for me is enough which comes with cuckoo-mod, so i hope someone else will can help you with your error to solve it

**Comment by marek2003** [comment] 2016-11-25 07:47
tks @doomedraven  and @KillerInstinct  for the support.

**Comment by spender-sandbox** [comment] 2016-12-13 15:41
Fixed via above commit.

-Brad

**Closed by spender-sandbox** 2016-12-13 15:41 UTC
